import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { Inter } from "next/font/google";
import ClientProvider from "@/components/provider/ClientProvider";
import ProviderApollo from "@/components/provider/ApolloProvider";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Twitter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressContentEditableWarning suppressHydrationWarning  >
          <SessionProvider>
            <ProviderApollo>
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                <ClientProvider>
                  {children}
                  <Toaster />
                </ClientProvider>
              </ThemeProvider>
            </ProviderApollo>
          </SessionProvider>
      </body>
    </html>
  );
}
